### PR TITLE
BIRD-15: Add exemplary model for audio classification

### PR DESCRIPTION
**Pull request by Cellmer**

### CODE REVIEW

**Comment by Cellmer** [comment]
It's just a placeholder, to be able to import from app. It's usable model form Kaggle though, example code testing it is here: https://www.kaggle.com/models/google/yamnet/tfLite

**Comment by gitesthuman** [comment]
It's not for merge, innit?

**Comment by Cellmer** [comment]
> It's not for merge, innit?

it is, just as a placeholder model ofc

**Comment by gitesthuman** [comment]
K bruv

**Review by gitesthuman — APPROVED** [review]

**Comment by Cellmer** [comment]
> K bruv

thanks mate

**Pull request merged**
